version: "3.7"

services:
  app:
    build: .
    image: $APP_IMAGE_TAG
    depends_on:
      - db
    environment:
      POSTGRES_URL: jdbc:postgresql://db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      SPRING_PROFILES_ACTIVE: postgres,test
    networks:
      - app_network
    ports:
      - $HOST_PORT:8080
    restart: &restart unless-stopped

  db:
    image: postgres:14.3-alpine
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    networks:
      - app_network
    restart: *restart
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  app_network:
