package ca.uqam.repriseexamen.model;

public enum TypeStatut {
    ENREGISTREE,
    SOUMISE,
    ANNULEE,
    EN_TRAITEMENT,
    ACCEPTEE_COMMIS,
    REJETEE_COMMIS,
    ACCEPTEE_DIRECTEUR,
    REJETEE_DIRECTEUR,
    ACCEPTEE_ENSEIGNANT,
    REJETEE_ENSEIGNANT,
    ACCEPTEE,
    REJETEE,
    DEMANDE_INFO,
    REPONSE_INFO,
    PLANIFIEE,
    ABSENCE,
    COMPLETEE,
    ARCHIVEE
}
