package ca.uqam.repriseexamen.model;

public enum TypeStatut {
    ENREGISTREE,
    SOUMISE,
    EN_TRAITEMENT,
    ACCEPTEE_COMMIS,
    REJETEE_COMMIS,
    ACCEPTEE_DIRECTEUR,
    REJETEE_DIRECTEUR,
    ACCEPTEE_ENSEIGNANT,
    REJETEE_ENSEIGNANT,
    PLANIFIEE,
    ANNULEE,
    COMPLETEE,
    ARCHIVEE
}
