package ca.uqam.repriseexamen.model;

public enum TypeDecision {
    ACCEPTATION_RECOMMANDEE,
    REJET_RECOMMANDE,
    ACCEPTEE_DIRECTEUR,
    REJETEE_DIRECTEUR,
    ACCEPTEE_ENSEIGNANT,
    REJETEE_ENSEIGNANT,
    AUCUNE
}
