version: "3.7"

services:
  nginx:
    build: .
    image: $NGINX_IMAGE_TAG
    networks:
      - test_app_network
      - prod_app_network
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt/:/etc/nginx/ssl/

networks:
  test_app_network:
    external: true
  prod_app_network:
    external: true
